### ISSUE TITLE
Strange behaviour of filter box

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/QueryLibrary#13]
For some strange reason the filter box in the table messes up the values in the fields:

![image](https://user-images.githubusercontent.com/7252105/86616667-78365080-bfb6-11ea-8a57-ef6cc98c170a.png)

If you search for something and then remove the filter the data is changed?? Must be something in the component.

Could be an old version of datatable on the OHDSI Shiny Server (https://data.ohdsi.org/QueryLibrary/ ) 

@bmosseveld can you reproduce this error when running it locally (we can also try it on our shiny io account)?

**Comment by bmosseveld** [comment]
Yes I can reproduce it.

**Comment by bmosseveld** [comment]
Solved
