### ISSUE TITLE
Documentation on database testing?

### ISSUE THREAD

**Issue by bdeboe** [OHDSI/QueryLibrary#25]
In `extras/Test.R` there appears to be functionality for running all queries from the .md files against one or more target databases (where it's looking into a /testdatabases folder that is scrubbed from the repo through `.gitignore`. That is almost exactly what I've been looking for as a means to test SqlRender coverage for a new database platform we'd like to support CDM and the OHDSI tools on. 
Is there any documentation or examples on using this script, before I try to reverse engineer all the details?

**Comment by bmosseveld** [comment]
This is an unadvertised feature.
I made a few changes to make it work again so make sure to pull the latest version.
Create a folder testdatabases in the inst/shinyApps/QueryLibrary folder and save there the database configuration .rds files of the databases you want to test.
Don't forget to set the environment variable DATABASECONNECTOR_JAR to the path of the database drivers and the working directory (line 6 of Test,R).

**Comment by bdeboe** [comment]
This is great, thanks so much for the additional information. It does exactly what I was looking for and saves me a lot of time. 
I only needed one tiny further extension to make it work for my new database platform (PRs for other repo's forthcoming ;-)), which I wrapped in PR #26 

Thanks again!
