### ISSUE TITLE
New types of queries for the library

### ISSUE THREAD

**Issue by natb1** [OHDSI/QueryLibrary#28]
Hello, I see a lot of value in the query library for my use case on health sites. I would like to contribute, and I have attached a proposal to do so. Please let me know if there is a preferred forum or form for this.

I find the query library to be very interesting because I think it is accessible for a broad variety of potential users, including (my particular interest) IT teams that may balk at a full stack deployment of OHDSI tools in a production environment. Regardless of an IT team's policies about managing a production environment, we'd ideally make the wealth of domain knowledge from the open source repos available to these stakeholders, and I think the query library is an ideal vehicle for that.

I propose (and volunteer for) an effort to review the suite of queries available in the data quality dashboard to make them available via the query library repo. I haven't reviewed this in detail with the DQD maintainers (maybe some of them are also maintainers here). I see [this](https://github.com/OHDSI/DataQualityDashboard/blob/HEAD/vignettes/SqlOnly.rmd) so there's a good chance something like this already exists. I just thought it could make sense to start here and see if something along those lines would be within the vision of the query library. I think making the DQD queries available via this repo would serve the educational function of the repo and (possibly) make this repo a good IT resource as well.

**Comment by fdefalco** [comment]
Thanks @natb1 . The QueryLibrary hasn't been reviewed or updated in quite a while so your focus on it would be much appreciated. Could we schedule some time to discuss a roadmap?

**Comment by natb1** [comment]
Very cool @fdefalco ty. I just reached out over email.

**Comment by natb1** [comment]
As described in #29
