### ISSUE TITLE
Create function in R Package to run all the queries as test

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/QueryLibrary#8]
Would be nice to have as package maintenance functionality:

Extract all the sql from all Markdown files and run them against a schema, catch errors and report back. Can take some time to run but would be good to have I think. We could ask people to run on different DBMSs.

EMC team is working on this and will pull this in.

**Comment by schuemie** [comment]
There are some OHDSI servers with simulated data available for testing in various platforms. These are for example [used to test FeatureExtraction](https://github.com/OHDSI/FeatureExtraction/tree/master/tests).

I will share the login details in a private message.

**Comment by PRijnbeek** [comment]
Test function is added that performs this
